name: "PR Title Checker"

# This workflow ensures that PR title adheres to conventional commits standard

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check_pr_title:
    name: "PR Title Checker"
    runs-on: ubuntu-latest
    steps:
      - name: Check type
        run: |
          VALID_COMMIT_TYPES="chore|ci|docs|feat|fix|refactor|test"
          REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((${VALID_COMMIT_TYPES})(\(.*\))?!?: .*))"

          COMMIT_MESSAGE="${{ github.event.pull_request.title }}"

          echo "Commit Message: ${COMMIT_MESSAGE}"

          if ! [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
            echo "::error title=Type::Incorrect type used. Valid types are ${VALID_COMMIT_TYPES}"
            exit 1
          else
            echo "::notice title=Type::All good"
          fi
